### ISSUE TITLE
Report error "ValueError: Unknown model type , exiting"

### ISSUE THREAD

**Issue by Alouette98** [vchoutas/expose#10]
System: Ubuntu 16.04, Python 3.7.9
After installing all prerequisites and putting models and data into the right place, I tried to run the demo python script, and it shows the error below.
`$ python demo.py --image-folder samples \
    --exp-cfg /p300/dataset/data/conf.yaml \
    --show=False \
    --output-folder ./result \
    --save-params False \
    --save-vis False \
    --save-mesh False
Processing with R-CNN:   0%|                                                                             | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/ap_expose/lib/python3.7/site-packages/torchvision/ops/boxes.py:101: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629403081/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  keep = keep.nonzero().squeeze(1)
Processing with R-CNN: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
2020-09-22 09:49:14.633 | INFO     | __main__:main:241 - Saving results to: ./result
2020-09-22 09:49:14.641 | WARNING  | expose.models.attention.predictor:__init__:92 - Apply hand network on body: True
2020-09-22 09:49:14.641 | WARNING  | expose.models.attention.predictor:__init__:94 - Apply hand network on hands: True
2020-09-22 09:49:14.641 | WARNING  | expose.models.attention.predictor:__init__:95 - Predict hands: True
2020-09-22 09:49:14.641 | WARNING  | expose.models.attention.predictor:__init__:102 - Predict head: True
2020-09-22 09:49:14.641 | INFO     | expose.models.attention.predictor:__init__:109 - Condition hand on body: True
2020-09-22 09:49:14.642 | INFO     | expose.models.attention.predictor:__init__:113 - Condition hand wrist pose on body: True
2020-09-22 09:49:14.642 | INFO     | expose.models.attention.predictor:__init__:118 - Condition hand finger pose on body: True
2020-09-22 09:49:14.642 | INFO     | expose.models.attention.predictor:__init__:122 - Condition hand shape on body shape: False
2020-09-22 09:49:14.642 | INFO     | expose.models.attention.predictor:__init__:169 - Condition head on body: True
2020-09-22 09:49:14.642 | INFO     | expose.models.attention.predictor:__init__:171 - Condition expression on body: True
2020-09-22 09:49:14.642 | INFO     | expose.models.attention.predictor:__init__:172 - Condition shape on body: False
2020-09-22 09:49:14.643 | INFO     | expose.models.attention.predictor:__init__:174 - Condition neck pose on body: False
2020-09-22 09:49:14.643 | INFO     | expose.models.attention.predictor:__init__:176 - Condition jaw pose on body: True
Traceback (most recent call last):
  File "demo.py", line 565, in <module>
    rcnn_batch=rcnn_batch,
  File "/root/anaconda3/envs/ap_expose/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "demo.py", line 244, in main
    model = SMPLXNet(exp_cfg)
  File "/p300/audiopose/expose/expose/models/smplx_net.py", line 39, in __init__
    self.smplx = build_attention_head(exp_cfg)
  File "/p300/audiopose/expose/expose/models/attention/build.py", line 23, in build_attention_head
    return SMPLXHead(cfg)
  File "/p300/audiopose/expose/expose/models/attention/predictor.py", line 251, in __init__
    **body_model_cfg)
  File "/root/anaconda3/envs/ap_expose/lib/python3.7/site-packages/smplx/body_models.py", line 2310, in build_layer
    raise ValueError(f'Unknown model type {model_type}, exiting!')
ValueError: Unknown model type , exiting!`

I wonder where the error is and how to fix this problem, thank you!

**Comment by mjoach** [comment]
Could you confirm you have downloaded and unpacked the SMPL-X model?

**Comment by vchoutas** [comment]
@Alouette98 I would guess that the SMPL-X model is not extracted in the correct sub-folder.

**Comment by Daniel-Kelvich** [comment]
Same problem. All models unpacked.

**Comment by booker-max** [comment]
您好，我现在出现了和您一样的问题，想问下您解决了么

**Comment by booker-max** [comment]
Do you have the training code for this paper? Can you share it with me? This is my email address 1654617276wj@gmail.com，Thank you very much.！

**Comment by Tetsujinfr** [comment]
@Alouette98  so I had the same issue and looking at the conf.yaml the path the code expects by default for models is data/models.

So, you need to dump your smplx models downloaded from [here](https://smpl-x.is.tue.mpg.de/) under /EXPOSE_DIR/data/models/

For instance for me that looks like:
```
/media/tetsfr/SSD/expose/data/models/smplx$ ls
SMPLX_FEMALE.npz  SMPLX_MALE.npz  SMPLX_NEUTRAL.npz  smplx_npz.zip
SMPLX_FEMALE.pkl  SMPLX_MALE.pkl  SMPLX_NEUTRAL.pkl  version.txt
```

Hope this helps. please close the issue if that is the case.

**Comment by francyzit** [comment]
Hi I have the same problem. How did you solve this problem?
