### ISSUE TITLE
Issues Generating STL Mesh

### ISSUE THREAD

**Issue by tdeeb** [vchoutas/expose#13]
I followed all the instructions for the demo, installed the dependencies, and have the pre-trained ExPose and SMPL-X models in the data folder. I initially ran the demo with `--save-mesh True`, but it didn't export the mesh nor throw any errors. Subsequent attempts are for some reason giving me errors with Qt, and I'm not sure if this is related to it not generating the mesh.
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "~/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.
```
I set `QT_QPA_PLATFORM=minimal` and it gets farther, but now I'm getting an error in Torch:
```
Traceback (most recent call last):
  File "demo.py", line 554, in <module>
    main(
  File "~/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "demo.py", line 461, in main
    axes[0, 1].imshow(out_img['rgb'][idx])
KeyError: 'rgb'
```
I'm running Python 3.8.2 on Linux Mint 20 Ulyana. Is there something I'm missing?

**Comment by tdeeb** [comment]
It turns out that one of the parameters used in the demo example threw this error. If I simply choose to export the mesh, I get a valid .ply file that I can then convert to .stl.
