### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by melih1996** [vchoutas/expose#32]
Hi, when I run the demo I got the error below:
Traceback (most recent call last):
  File "demo.py", line 32, in <module>
    import open3d as o3d
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/open3d/__init__.py", line 56, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/open3d/cpu/pybind.cpython-36m-x86_64-linux-gnu.so)

**Comment by melih1996** [comment]
I have resolved it by updating my os from ubuntu 16 to 18 but then I got another error below:
Traceback (most recent call last):
  File "demo.py", line 565, in <module>
    rcnn_batch=rcnn_batch,
  File "/home/melih/anaconda3/envs/ai/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "demo.py", line 366, in main
    bg_imgs=bg_hd_imgs,
UnboundLocalError: local variable 'bg_hd_imgs' referenced before assignment

**Comment by booker-max** [comment]
Do you have the training code for this paper? Can you share it with me? This is my email address 1654617276wj@gmail.com，Thank you very much.！
