### ISSUE TITLE
Request for SMPL-X 1.0 Model

### ISSUE THREAD

**Issue by Carrotn** [vchoutas/expose#65]
I have noticed that the checkpoint for the ExPose , which I am utilizing, is built upon the SMPL-X 1.0 . Unfortunately, I can only find the SMPL-X 1.1 version available for download on SMPLX website.

Could you please assist me in obtaining the SMPL-X 1.0 model?  Any help or guidance on how to access this version would be greatly appreciated.

**Comment by MosaabRkia** [comment]
same here getting this long error
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=KeypointRCNN_ResNet50_FPN_Weights.COCO_V1`. You can also use `weights=KeypointRCNN_ResNet50_FPN_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/keypointrcnn_resnet50_fpn_coco-fc266e95.pth" to /root/.cache/torch/hub/checkpoints/keypointrcnn_resnet50_fpn_coco-fc266e95.pth
100% 226M/226M [00:03<00:00, 78.0MB/s]
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Processing with R-CNN: 100% 1/1 [00:04<00:00,  4.10s/it]
2024-05-19 18:15:30.463 | INFO     | __main__:main:241 - Saving results to: /content/expose/output
2024-05-19 18:15:30.468 | WARNING  | expose.models.attention.predictor:__init__:91 - Apply hand network on body: True
2024-05-19 18:15:30.468 | WARNING  | expose.models.attention.predictor:__init__:93 - Apply hand network on hands: True
2024-05-19 18:15:30.469 | WARNING  | expose.models.attention.predictor:__init__:95 - Predict hands: True
2024-05-19 18:15:30.469 | WARNING  | expose.models.attention.predictor:__init__:102 - Predict head: True
2024-05-19 18:15:30.469 | INFO     | expose.models.attention.predictor:__init__:109 - Condition hand on body: True
2024-05-19 18:15:30.469 | INFO     | expose.models.attention.predictor:__init__:112 - Condition hand wrist pose on body: True
2024-05-19 18:15:30.469 | INFO     | expose.models.attention.predictor:__init__:117 - Condition hand finger pose on body: True
2024-05-19 18:15:30.469 | INFO     | expose.models.attention.predictor:__init__:121 - Condition hand shape on body shape: False
2024-05-19 18:15:30.469 | INFO     | expose.models.attention.predictor:__init__:169 - Condition head on body: True
2024-05-19 18:15:30.470 | INFO     | expose.models.attention.predictor:__init__:170 - Condition expression on body: True
2024-05-19 18:15:30.470 | INFO     | expose.models.attention.predictor:__init__:172 - Condition shape on body: False
2024-05-19 18:15:30.470 | INFO     | expose.models.attention.predictor:__init__:173 - Condition neck pose on body: False
2024-05-19 18:15:30.470 | INFO     | expose.models.attention.predictor:__init__:175 - Condition jaw pose on body: True
Traceback (most recent call last):
  File "/content/expose/demo.py", line 554, in <module>
    main(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/expose/demo.py", line 244, in main
    model = SMPLXNet(exp_cfg)
  File "/content/expose/expose/models/smplx_net.py", line 39, in __init__
    self.smplx = build_attention_head(exp_cfg)
  File "/content/expose/expose/models/attention/build.py", line 23, in build_attention_head
    return SMPLXHead(cfg)
  File "/content/expose/expose/models/attention/predictor.py", line 247, in __init__
    self.body_model = build_body_model(
  File "/usr/local/lib/python3.10/dist-packages/smplx/body_models.py", line 2345, in build_layer
    raise ValueError(f'Unknown model type {model_type}, exiting!')
ValueError: Unknown model type , exiting!

i have downloaded the checkpoints, and the smplx model too like that 

expose/data/models/smplx$ ls
SMPLX_FEMALE.npz  SMPLX_MALE.npz  SMPLX_NEUTRAL.npz  smplx_npz.zip
SMPLX_FEMALE.pkl  SMPLX_MALE.pkl  SMPLX_NEUTRAL.pkl  version.txt
